<?php $date = ("" !== $this->value) ? date('d/m/Y', $this->value): ""; ?>
<input type="hidden" id="<?php echo $this->getObject()->getUid(); ?>_type" name="<?php echo $this->getObject()->getUid(); ?>_type"  value="<?php echo get_class($this->getObject()); ?>" />
<label for="<?php echo $this->getObject()->getUid(); ?>" style="font-weight: bold;"><?php echo $this->getObject()->getLabel(); ?></label>
<div style="text-align: right;"><input id="<?php echo $this->getObject()->getUid(); ?>_delete" type="checkbox" <?php if (!$this->getObject()->isLoaded()) :?>checked="checked"<?php endif;?>><label for="<?php echo $this->getObject()->getUid(); ?>_delete" style="min-width: 0px;">&nbsp;Supprimer</label></div>
<div id="<?php echo $this->getObject()->getUid(); ?>_container">
    <input class="date_pick_form" id="<?php echo $this->getObject()->getUid(); ?>" name="<?php echo $this->getObject()->getUid(); ?>" style="margin-bottom: 10px;" value="<?php echo $date; ?>" data-value="<?php print $this->value; ?>" />
</div>