<input type="hidden" id="<?php echo $this->getObject()->getUid(); ?>_type" name="<?php echo $this->getObject()->getUid(); ?>_type"  value="<?php echo get_class($this->getObject()); ?>"/>
<label for="<?php echo $this->getObject()->getUid(); ?>" style="font-weight: bold;"><?php echo $this->getObject()->getLabel(); ?></label>
<div style="text-align: right;">
<?php if (false === $this->getParam('disabled')): ?>
    <input id="<?php echo $this->getObject()->getUid(); ?>_delete" type="checkbox" <?php if (!$this->getObject()->isLoaded()) :?>checked="checked"<?php endif;?>><label for="<?php echo $this->getObject()->getUid(); ?>_delete" style="min-width: 0px;">&nbsp;Supprimer</label>
<?php endif; ?>
</div>
<div <?php if (false === $this->getParam('disabled')) echo 'id="'.$this->getObject()->getUid().'_container"'; ?> class="bbImagePreview" style="width: 100%; height: 150px; padding-top: 20px;">
    <?php if ($this->path) : ?>
        <div class="preview">
            <span class="imageHolder">
                <img src="<?php echo $this->getUri('/images/'.$this->path); ?>?<?php echo time();?>" />
                <span class="uploaded"></span>
            </span>
        </div>
    <?php endif; ?>
</div>
<input type="hidden" id="<?php echo $this->getObject()->getUid(); ?>" name="<?php echo $this->getObject()->getUid(); ?>"  value="" />


<div id="imagebbselector-editpreview-tpl" style="display:none;">
    <div class="preview">
        <span class="imageHolder">
            <img />
            <span class="uploaded"></span>
        </span>
        <div class="progressHolder">
            <div class="progress"></div>
        </div>
    </div>
</div>