<?php $options = $this->getParam('options'); ?>
<?php $options = is_array($options) ? reset($options) : array(); ?>
<input type="hidden" id="<?php echo $this->getObject()->getUid(); ?>_type" name="<?php echo $this->getObject()->getUid(); ?>_type"  value="<?php echo get_class($this->getObject()); ?>" />
<label for="<?php echo $this->getObject()->getUid(); ?>" style="font-weight: bold;"><?php echo $this->getObject()->getLabel(); ?></label>
<div id="<?php echo $this->getObject()->getUid(); ?>_container">
	<select id="<?php echo $this->getObject()->getUid(); ?>" name="<?php echo $this->getObject()->getUid(); ?>" style="margin-bottom: 10px;">>
		<option value="">-- Sélectionner --</option>
		<?php foreach($options as $key => $value): ?>
		<option value="<?php echo $key; ?>"<?php if ($this->value == $key) echo ' selected="selected"'; ?>><?php echo $value; ?></option>
		<?php endforeach; ?>
	</select>
</div>