
parameters:

    bbapp.routing.class: BackBuilder\Routing\RouteCollection

    bbapp.routing.image_uri_prefix: images
    bbapp.routing.media_uri_prefix: media
    bbapp.routing.resource_uri_prefix: ressources

    classcontent_thumbnail.base_folder: img/contents
    classcontent_thumbnail.extension: png

services:

    routing:
        class:      %bbapp.routing.class%
        arguments:  ["@bbapp"]
        tags:
            - { name: "dumpable", dispatch_event: false }
