language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm-nightly

install: composer install --prefer-dist --no-interaction

script:
    - phpunit

notifications:
    email: false
