language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=weak

matrix:
    allow_failures:
        - php: 7.0

before_script:
  - phpenv config-add ./Tests/travis.php.ini
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit

notifications:
    email: false
