language: php

sudo: false

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=weak

matrix:
    allow_failures:
        - php: 7.0
    fast_finish: true

before_install:
  - composer self-update
  - if [ "$TRAVIS_BRANCH" = "master" ]; then export COMPOSER_ROOT_VERSION=dev-master; else export COMPOSER_ROOT_VERSION="$TRAVIS_BRANCH".x-dev; fi;
 
before_script:
  - phpenv config-add ./Tests/travis.php.ini
  - phpenv config-rm xdebug.ini
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit

notifications:
    email: false
