<form id="form-imagebbselector-edit-<?php echo $this->getObject()->getUid(); ?>">
    <fieldset>
        <input type="hidden" name="uid" value="<?php echo $this->getObject()->getUid(); ?>" />
        <label for="<?php echo $this->title->getUid(); ?>"><?php echo $this->title->getLabel(); ?></label>
        <input type="text" id="<?php echo $this->title->getUid(); ?>" name="title" value="<?php echo htmlentities($this->title->value, ENT_COMPAT, 'UTF-8'); ?>" style="width: 100%; margin-bottom: 10px;" />

        <label for="<?php echo $this->description->getUid(); ?>"><?php echo $this->description->getLabel(); ?></label>
        <textarea id="<?php echo $this->description->getUid(); ?>" name="description" style="width: 100%; height: 100px; margin-bottom: 10px;"><?php echo htmlentities($this->description->value, ENT_QUOTES, "UTF-8"); ?></textarea>

        <label for="<?php echo $this->copyrights->getUid(); ?>"><?php echo $this->copyrights->getLabel(); ?></label>
        <textarea id="<?php echo $this->copyrights->getUid(); ?>" name="copyrights" style="width: 100%; height: 50px; margin-bottom: 10px;"><?php echo htmlentities($this->copyrights->value, ENT_QUOTES, "UTF-8"); ?></textarea>
            
        <label for="<?php echo $this->image->getUid(); ?>"><?php echo $this->image->getLabel(); ?></label>
        <div id="<?php echo $this->image->getUid(); ?>" class="bbImagePreview bbMediaPreview" data-mediatype="image" style="width: 100%; height: 150px; padding-top: 20px;">
            <?php if ($this->image->path) :?>
            <div class="preview">
                <span class="imageHolder">
                    <img src="<?php echo $this->getUri('/images/'.$this->image->path); ?>?<?php echo time();?>" />
                    <span class="uploaded"></span>
                </span>
            </div>
            <?php endif;?>
        </div>
        <input class="uploadedmedia" type="hidden" name="uploadedmedia" data-fieldname="image" value="" />
    </fieldset>
</form>

<div id="imagebbselector-editpreview-tpl" style="display:none;">
    <div class="preview">
        <span class="imageHolder">
            <img />
            <span class="uploaded"></span>
        </span>
        <div class="progressHolder">
            <div class="progress"></div>
        </div>
    </div>
</div>