<?php // T3_1 ?>
<div class="bb5-tabarea-31">
    <fieldset>
        <legend>Edition du thème graphique courant</legend>
        <div id="lessVariablesEditables"></div>
        <div class="bb5-tabarea_content">
            <p><label>bodyBackground </label><button class="bb5-colorsample bb5-colorpicker" style="background-color:white;"></button></p>
            <p><label>baseFontFamily </label>
                <select name="fonts" class="bb5-select inputLessVariables">
                    <option value="Arial">Arial</option>
                    <option value="Arial Black">Arial Black</option>
                    <option value="Castellar">Castellar</option>
                    <option value="Comic Sans MS">Comic Sans MS</option>
                    <option value="Century Gothic">Century Gothic</option>
                    <option value="Copperplate Gothic Light">Copperplate Gothic Light</option>
                    <option value="Courier New">Courier New</option>
                    <option value="Curlz MT">Curlz MT</option>
                    <option value="Elephant">Elephant</option>
                    <option value="French Script MT">French Script MT</option>
                    <option value="Helvetica">Helvetica</option>
                    <option value="Lucida Sans">Lucida Sans</option>
                    <option value="MS Sans Serif">MS Sans Serif</option>
                    <option value="Script MT Bold">Script MT Bold</option>
                    <option value="Times New Roman">Times New Roman</option>
                    <option value="Verdana, Geneva, sans-serif" selected="selected">Verdana, Geneva, sans-serif</option>
                    <option value="Helvetica Neue, Helvetica, Arial, sans-serif">Helvetica Neue, Helvetica, Arial, sans-serif</option>
                </select>
            </p>
        </div>
        <div class="bb5-tabarea_content">
            <p><label>textColor </label><button class="bb5-colorsample bb5-colorpicker" style="background-color:#333;"></button></p>
            <p><label>linkColor </label><button class="bb5-colorsample bb5-colorpicker" style="background-color:orange;"></button></p>
            <p><label>linkColorHover </label><button class="bb5-colorsample bb5-colorpicker" style="background-color:orange;"></button></p>
        </div>
        <div class="bb5-tabarea_content">
            <p><label>navbarBackground </label><button class="bb5-colorsample bb5-colorpicker" style="background-color:blue;"></button></p>
            <p><label>navbarBackgroundHighlight </label><button class="bb5-colorsample bb5-colorpicker" style="background-color:lightblue;"></button></p>
            <p><label>linkColorHover </label><button class="bb5-colorsample bb5-colorpicker" style="background-color:marine;"></button></p>
        </div>
        <div class="bb5-tabarea_content">
            <p><label>navbarText </label><button class="bb5-colorsample bb5-colorpicker" style="background-color:white;"></button></p>
            <p><label>navbarLinkColor </label><button class="bb5-colorsample bb5-colorpicker" style="background-color:white;"></button></p>
            <p><label>dropdownLinkBackgroundHover </label><button class="bb5-colorsample bb5-colorpicker" style="background-color:beige;"></button></p>
        </div>
    </fieldset>
</div>
<?php // T3_2 ?>
<div class="bb5-tabarea-32 bb5-tabarea_has-editfield">
    <?php // ?>
    <fieldset>
        <legend>Thème</legend>
        <p class="bb5-tabarea_editfield"><input type="text" placeholder="nom du thème"><button title="Editer le nom" class="bb5-button bb5-ico-edit bb5-button-square"></button></p>
        <div class="bb5-tabarea_content">
            <p><button class="bb5-button bb5-ico-save bb5-BtnGridSaveTheme">Enregistrer</button></p>
        </div>
        <?php // begin tabdrawer ?>
        <div class="bb5-tabdrawer-wrapper"><a href="#" class="bb5-tabdrawer-toggle showTplTheme">Autres thèmes<span></span></a>
            <div class="bb5-tabdrawer-data" id="bb5-tplThemeContainer">
                <div class="bb5-tabdrawer-padding">
                    <ul id="bb5-theme-extra">
                        <li><label><button class="bb5-button bb5-button-bulky bb5-theme-choice-1" title="Choisr ce thème n°1"></button> Thème par défaut</label></li>
                        <li><label><button class="bb5-button bb5-button-bulky bb5-theme-choice-2" title="Choisr ce thème n°2"></button> Thème N°2</label></li>
                        <li><label><button class="bb5-button bb5-button-bulky bb5-theme-choice-3" title="Choisr ce thème n°3"></button> Thème N°3</label></li>
                        <li><label><button class="bb5-button bb5-button-bulky bb5-theme-choice-4" title="Choisr ce thème n°4"></button> Thème N°4</label></li>
                        <li><label><button class="bb5-button bb5-button-bulky bb5-theme-choice-5" title="Choisr ce thème n°5"></button> Thème N°5</label></li>
                        <li><label><button class="bb5-button bb5-button-bulky bb5-theme-choice-6" title="Choisr ce thème n°6"></button> Thème N°6</label></li>
                    </ul>
                </div>
            </div>
        </div>
        <?php // end tabdrawer ?>

    </fieldset>
</div>