<?php // T5_1 ?>
<div class="bb5-tabarea-51">
    <?php // 51 ?>
    <fieldset>
        <legend data-i18n="toolbar.status.content_validation"><?php echo $this->__('Content validation') ?></legend>
        <?php // 521 ?>
        <div class="bb5-tabarea_content">
            <p><button class="bb5-button bb5-ico-commit" data-i18n="toolbar.status.content_commit">Valider</button></p>
            <p><button class="bb5-button bb5-ico-refresh" data-i18n="toolbar.status.content_refresh">Rafraîchir</button></p>
            <p><button class="bb5-button bb5-ico-cancel" data-i18n="toolbar.status.content_cancel">Rétablir</button></p>
        </div>
    </fieldset>
    <?php // end 51 ?>
</div>
<div class="bb5-tabarea-52">
    <?php // 52 ?>
    <fieldset>
        <legend data-i18n="toolbar.status.page_status">Statut de la page</legend>
        <?php // 512 ?>
        <div class="bb5-tabarea_content">
            <p>
                <label for="bb5-form-online-toggle" data-i18n="toolbar.status.page_online">En ligne</label>
                <span class="bb5-ios-switch bb5-switch-online">
                    <input id="bb5-pageOnline" type="checkbox" name="page-online" value="1">
                </span>
            </p>
            <?php // begin tabdrawer ?>
            <div class="bb5-tabdrawer-wrapper"><a href="#" class="bb5-tabdrawer-toggle" data-i18n="toolbar.status.page_options">Options de mise en ligne<span></span></a>
                <div class="bb5-tabdrawer-data">
                <div class="bb5-tabdrawer-padding">
                    <fieldset>
                        <legend data-i18n="toolbar.status.scheduling">Programmation de la mise en ligne</legend>
                        <p><label for="bb5-form-online-startdate" data-i18n="toolbar.status.online_date">Date de mise en ligne</label> <input type="text" id="bb5-form-online-startdate"></p>
                        <p><label for="bb5-form-online-autoarchive" data-i18n="toolbar.status.offline_date">Date d'auto-archivage</label> <input type="text" id="bb5-form-online-autoarchive"></p>
                    </fieldset>
                </div>
                </div>
            </div>
            <?php // end tabdrawer ?>
        </div>
        <?php // 513 ?>
        <div class="bb5-tabarea_content">
            <p><label for="bb5-form-hidden-toggle" data-i18n="toolbar.status.page_visible">Visible dans les menus</label>
            <span class="bb5-ios-switch bb5-switch-hidden">
                <input id="bb5-pageHidden" type="checkbox" name="page-hidden" value="2">
            </span>
            </p>
        </div>
        <?php // 511 ?>
        <div class="bb5-tabarea_content">
            <p><button class="bb5-button bb5-ico-save" data-i18n="toolbar.status.page_save">Enregistrer</button></p>
            <p><button class="bb5-button bb5-ico-edit" data-i18n="toolbar.status.page_edit">Modifier</button></p>
            <p><button class="bb5-button bb5-ico-del" data-i18n="toolbar.status.page_delete">Supprimer</button></p>
        </div>
    </fieldset>
    <?php // end 52?>
</div>
<?php // T5_2 ?>