<?php // T1_1 ?>
<div class="bb5-tabarea-11">
    <fieldset>
        <legend data-i18n="toolbar.templates.choose">Choisir un gabarit</legend>
        <?php //userTemplate ?>
        <div id="bb5-use-template-wrapper" class="bb5-tabarea_content">
            <div id="bb5-slider-layout-wrapper" class="bb5-slider-layout-wrapper slider-fx">
                <ul id="bb5-slider-layout"></ul>
            </div>
        </div>

        <?php // Tempalte model ?>
        <div class="bb5-tabdrawer-wrapper"><a href="#" class="bb5-tabdrawer-toggle" data-i18n="toolbar.templates.other_templates">Autres modèles<span></span></a>
            <div class="bb5-tabdrawer-data bb5-tplModelContainer">
                <div id="bb5-tplModelContainer" class="bb5-tabdrawer-padding">
                    <ul id="bb5-layout-extra"></ul>
                </div>
            </div>
        </div>
        <?php // end tabdrawer ?>

    </fieldset>
</div>
<?php // T1_2 ?>
<div class="bb5-tabarea-12 bb5-tabarea_has-editfield">
    <fieldset>
        <legend data-i18n="toolbar.templates.template">Gabarit</legend>
        <p class="bb5-tabarea_editfield"><input readonly id="bb5-layoutNameField" type="text" placeholder="Nom du gabarit" data-i18n="placeholder:toolbar.templates.template_name"><button title="Editer le nom" data-i18n="title:toolbar.templates.edit_template" class="bb5-button bb5-ico-edit bb5-ico-edit-layout bb5-button-square"></button></p>
        <div class="bb5-tabarea_content">
            <p style="display:none;"><button class="bb5-button bb5-ico-clone" data-i18n="toolbar.templates.duplicate">Dupliquer</button></p>
            <p><button class="bb5-button bb5-ico-save" data-i18n="toolbar.templates.save">Enregistrer</button></p>
            <p><button class="bb5-button bb5-ico-del" data-i18n="toolbar.templates.delete">Supprimer</button></p>
        </div>
    </fieldset>
</div>
<?php // T1_3 ?>
<div class="bb5-tabarea-13 bb5-tabarea_has-editfield">
    <fieldset>
        <legend data-i18n="toolbar.templates.area">Zone</legend>
        <p class="bb5-tabarea_editfield"><input id="bb5-zoneNameField" type="text" placeholder="Nom de la zone" data-i18n="placeholder:toolbar.templates.area_name"><button title="Editer le nom" data-i18n="title:toolbar.templates.edit_area" class="bb5-button bb5-ico-edit bb5-ico-edit-zone bb5-button-square"></button></p>
        <div class="bb5-tabarea_content">
            <p><button class="bb5-button bb5-ico-splitzoneh" data-i18n="toolbar.templates.hsplit">Scinder horizontalement</button></p>
            <p><button class="bb5-button bb5-ico-splitzonev" data-i18n="toolbar.templates.vsplit">Scinder verticalement</button></p>
            <p><button class="bb5-button bb5-ico-delzone" data-i18n="toolbar.templates.delete_area">Supprimer la zone</button></p>
        </div>
    </fieldset>
</div>
<?php // T1_4 ?>
<div class="bb5-tabarea-14">
    <fieldset>
        <legend data-i18n="toolbar.templates.grid">Grille</legend>
        <div class="bb5-tabarea_content">
            <p><span  data-i18n="toolbar.templates.grid_width">Largeur de la grille :</span> <strong>960</strong> (pixels)</p>
            <p><label><input id="bb5-showGridBtn" type="checkbox" name="grid"> <span data-i18n="toolbar.templates.show_grid">Afficher la grille</span></label></p>
        </div>
        <?php // begin tabdrawer ?>
        <div class="bb5-tabdrawer-wrapper"><a href="#" class="bb5-tabdrawer-toggle bb5-gridConstant" data-i18n="toolbar.templates.edit_grid">Modifier la grille <span></span></a>
            <div class="bb5-tabdrawer-data bb5-grid-extras">
                <div class="bb5-tabdrawer-padding">
                    <p><label data-i18n="toolbar.templates.num_columns">Nombre de colonnes</label> <span><strong>12</strong></span></p>
                    <p><label date-i18n="toolbar.templates.column_width">Largeur (pixels)</label> <input id="colSizeField" type="text" size="2" value="60"> <button type="button" class="bb5-button bb5-button-square gridColBtn upAction" title="Incrémenter le nombre" data-i18n="title:toolbar.templates.increase">+</button> <button class="bb5-button bb5-button-square gridColBtn downAction" title="Décrémenter le nombre" data-i18n="title:toolbar.templates.decrease">-</button></p>
                    <p><label data-i18n="toolbar.templates.gutter_width">Gouttière (pixels)</label> <input id="gutterSizeField" type="text" size="2" value="10"> <button class="bb5-button bb5-button-square gutterBtn upAction" title="Incrémenter le nombre" data-i18n="title:toolbar.templates.increase">+</button> <button class="bb5-button bb5-button-square gutterBtn downAction" title="Décrémenter le nombre" data-i18n="title:toolbar.templates.decrease">-</button></p>
                    <p class="bb5-txt-align-right"><button class="bb5-button bb5-button-square bb5-gridConstant-validate" data-i18n="toolbar.templates.save_grid">Valider</button></p>
                </div>
            </div>
        </div>
        <?php // end tabdrawer ?>
    </fieldset>
</div>