<?php // T6_1 ?>
<div class="bb5-tabarea-61">
    <?php // 61 ?>
    <fieldset>
        <legend data-i18n="toolbar.bundles.choose">Choisissez une extension</legend>
        <?php // 611 ?>
        <div id="bb5-use-bundle-wrapper" class="bb5-tabarea_content">
            <div class="bb5-slider-extnd-wrapper slider-fx">
                <ul id="bb5-slider-extnd"></ul>
            </div>
        </div>
    </fieldset>
    <?php // end 61 ?>
</div>
<?php // End T6_1 ?>
<?php // T6_2 ?>
<div class="bb5-tabarea-62">
    <fieldset>
        <legend id="bb5-use-bundle-name"></legend>
        <div  id="bb5-use-bundle-access" class="bb5-tabarea_content"></div>
    </fieldset>
</div>
<?php // End T6_2 ?>