<script type="text/javascript" src="<?php echo $this->getUri('ressources/js/libs/jquery-1.7.2.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->getUri('ressources/js/bb.js'); ?>" id="bb5-scripts"></script>

<!--handle custom script-->
<?php
$layoutScripts = $this->getParam("scripts");
$layoutCss = $this->getParam("css");
$layoutScriptsArr = (is_array($layoutScripts)) ? $layoutScripts : (array) $layoutScripts;
$layoutCssArr = (is_array($layoutCss)) ? $layoutCss : (array) $layoutCss;
?>

<!--layout scripts-->
<?php foreach ($layoutScriptsArr as $script): ?>
    <script type="text/javascript" src="<?php echo $this->getUri($script); ?>"></script>
<?php endforeach; ?>

<link rel="stylesheet" href="<?php echo $this->getUri('ressources/css/ui-lightness/jquery-ui-1.8.21.custom.css'); ?>">
<link rel="stylesheet" href="<?php echo $this->getUri('ressources/css/bb5_ui.css'); ?>">
<!--layout css-->
<?php foreach ($layoutCssArr as $css): ?>
    <link rel="stylesheet" href="<?php echo $this->getUri($css); ?>"></link>
<?php endforeach; ?>

<?php if (NULL !== $this->getParam('token') && is_a($this->getParam('token'), 'BackBuilder\Security\Token\BBUserToken')): ?>
   <!-- not used <script src="<?php echo $this->getUri('ressources/js/aloha/lib/aloha.js'); ?>" data-aloha-plugins="common/format, common/link, common/highlighteditables, common/paste, common/block, common/commands, extra/bbselector <?php echo (('' != $this->getParam('aloha_extraplugins')) ? (', ' . $this->getParam('aloha_extraplugins')) : ''); ?>" type="text/javascript"></script>-->
    <link rel="stylesheet" href="<?php echo $this->getUri('ressources/js/libs/alohaeditor/aloha/css/aloha.css'); ?>">

    <?php // BB5 interface ?>
    <link rel="stylesheet" href="<?php echo $this->getUri('ressources/css/jquery-ui-select.css'); ?>">
    <link rel="stylesheet" href="<?php echo $this->getUri('ressources/css/loadmask/jquery.loadmask.css'); ?>">
    <?php //CSS: Aloha ?>
    <link rel="stylesheet" href="<?php echo $this->getUri('ressources/js/aloha/css/aloha.css'); ?>" type="text/css">
    <?php // Bootstrap ?>
    <link rel="stylesheet" href="<?php echo $this->getUri('ressources/css/colorpicker.css'); ?>">

    <?php // end script and style ?>
    <div id="bb5-toolbar-wrapper" data-site="<?php echo $this->getCurrentSite()->getUid(); ?>" data-layout="<?php echo $this->layout()->getUid(); ?>" data-page="<?php echo $this->currentpage()->getUid(); ?>" data-breadcrumb="<?php echo join('-', $this->currentpage()->getBreadcrumb_uids()); ?>">
        <?php // Begin toolbar wrapper ?>
        <p id="bb5-logo">
            <a href="http://www.backbuilder.fr/" target="_blank">
                <img src="<?php echo $this->getUri('ressources/img/bb5_logo_full_sm.png'); ?>" alt="BackBuilder5™">
            </a>
            <span><b> Create</b> your Website</span>
        </p>
        <p id="bb5-topmost-toolbar">
            <?php /*
              <button class="bb5-tiny-button bb5-ico-clue"></button>
              <button class="bb5-tiny-button bb5-ico-help"></button>
             */ ?>
            <span id="bb5-i18n-choice"></span>
            <span id="bb5-topmost-login">
                <button class="bb5-tiny-button bb5-ico-cross"></button>
            </span>
        </p>
        <div id="bb5-toolbar">
            <?php // INNER TOOLBAR ?>
            <p id="bb5-shortcuts">
                <button class="bb5-button bb5-ico-commit bb5-invert" data-i18n="toolbar.save">Enregistrer</button>
                <button class="bb5-button bb5-ico-refresh bb5-invert" data-i18n="toolbar.refresh">Rafraîchir</button>
                <button class="bb5-button bb5-ico-cancel bb5-invert" data-i18n="toolbar.cancel">Annuler</button>
            </p>
            <?php // BB5 MAINTABS ?>
            <div id="bb5-maintabs">
                <ul class='bb5-tabs'>
                    <li<?php if (false === $this->getApplication()->getSecurityContext()->isGranted('sudo')
                && false === $this->getApplication()->getSecurityContext()->isGranted('EDIT', new \BackBuilder\Site\Layout('*')))
            echo ' style="display:none;"';
        ?>>
                        <a href='#bb5-grid' data-i18n="toolbar.templates.label">Gabarits</a>
                    </li>
                    <li style="display: none;">
                        <a href='#bb5-blocks' data-i18n="toolbar.blocks">Blocs</a>
                    </li>
                    <li style="display: none;">
                        <a href='#bb5-theming' data-i18n="toolbar.themes">Thèmes</a>
                    </li>
                    <li>
                        <a href='#bb5-editing' data-i18n="toolbar.edition">Edition</a>
                    </li>
                    <li style="display: none;">
                        <a href='#bb5-status' data-i18n="toolbar.status_title">Validation et statut</a>
                    </li>
                    <li>
                        <a href='#bb5-bundle' data-i18n="toolbar.bundles_title">Extensions</a>
                    </li>
                    <li style="display: none;">
                        <a href='#bb5-personal' data-i18n="toolbar.my_space">Mon espace</a>
                    </li>
                </ul>
                <div id="bb5-grid" style="display:none">
                    <?php // Begin Tabbed Grid ?>
    <?php echo $this->partial('bb5/_bb5.tab.grid.phtml'); ?>
    <?php // End Tabbed Grid  ?>
                </div>
                <div id="bb5-blocks" style="display:none">
                    <p data-i18n="toolbar.blocks">Gestion des blocs - dev en cours - [bb5-blocks]</p>
                </div>
                <div id="bb5-theming" style="display:none">
                    <?php // Begin Tabbed Theming ?>
    <?php echo $this->partial('bb5/_bb5.tab.theming.phtml'); ?>
                    <?php // End Tabbed Theming  ?>
                </div>
                <div id='bb5-editing' style="display:none">
                    <?php // Begin Tabbed Editing ?>
    <?php echo $this->partial('bb5/_bb5.tab.editing.phtml'); ?>
                    <?php // End Tabbed Editing  ?>
                </div>
                <div id="bb5-status" style="display:none">
                    <?php // Begin Tabbed Status ?>
    <?php echo $this->partial('bb5/_bb5.tab.status.phtml'); ?>
                    <?php // End Tabbed Status  ?>
                </div>
                <div id="bb5-bundle" style="display:none;">
                    <?php // Begin Tabbed Extensions ?>
    <?php echo $this->partial('bb5/_bb5.tab.extensions.phtml'); ?>
    <?php // End Tabbed Extensions  ?>
                </div>
                <div id='bb5-personal' style="display:none">
                    <p>And this is the 5th tab.</p>
                </div>
            </div>
        <?php // END BB5 MAINTABS  ?>
        <?php // END INNER TOOLBAR ?>
        </div>
        <?php // End toolbar wrapper ?>

    <?php // Exam Path Wrapper  ?>
        <div id="bb5-exam-path-outter">
            <div id="bb5-exam-path-wrapper" style="display:none">
                <div id="bb5-exam-path-inner">
                    <a class="bb5-ico-pathupwards"><span class="visuallyhidden" data-i18n="toolbar.path_back">Remonter</span></a>
                    <p id="bb5-exam-path"><a href="#">Root</a> <a href="#">item 001</a> <a href="#" class="bb5-exam-path-current-item">001-1</a></p>
                    <a class="bb5-ico-pathclose"><span class="visuallyhidden" data-i18n="toolbar.path_close">Refermer la barre</span></a>
                </div>
            </div>
        </div>
    <?php // End Exam Path Wrapper  ?>
    <?php echo $this->partial('bb5/_bb5.widgets.templates.phtml'); ?>
    </div>
    <section id="bb-box-wrapper"></section>

    <script type="text/javascript">
        $(document).ready(function() {
            bb.start();
            //AlohaManager.init();
        });
    </script>
<?php endif; ?>