<?php //if (NULL !== $this->getParam('token') && is_a($this->getParam('token'), 'BackBuilder\Security\Token\BBUserToken')): ?>
    <link rel="stylesheet" href="<?php echo $this->getUri('resources/html/css/bootstrap.min.css') ?>">
    <link rel="stylesheet" href="<?php echo $this->getUri('resources/html/css/bb5-skin03.css') ?>">
    <link rel="stylesheet" href="<?php echo $this->getUri('resources/html/css/bootsrap-grid.css') ?>">
    <link rel="stylesheet" href="<?php echo $this->getUri('resources/html/css/bootsrap-resp-grid.css') ?>">
    <link rel="stylesheet" href="<?php echo $this->getUri('resources/html/css/jquery-ui.css') ?>">
    <link rel="stylesheet" href="<?php echo $this->getUri('resources/html/css/font-awesome.min.css') ?>">
    <link rel="stylesheet" href="<?php echo $this->getUri('resources/html/css/bootstrap.css') ?>">
    <link rel="stylesheet" href="<?php echo $this->getUri('resources/html/css/bb5-ui.css') ?>">
    <link rel="stylesheet" href="<?php echo $this->getUri('resources/html/css/font-awesome.css') ?>">
    <link rel="stylesheet" href="<?php echo $this->getUri('resources/lib/datetimepicker/jquery.datetimepicker.css') ?>">
    <link rel="stylesheet" href="<?php echo $this->getUri('resources/html/css/fix.css') ?>">
<?php //endif; ?>