<?php $current_page = $this->getParam('current_page'); ?>

<div id="bb5-ui"
     data-site-uid="<?php echo $current_page->getSite()->getUid() ?>"
     data-page-uid="<?php echo $current_page->getUid() ?>"
     data-layout-uid="<?php echo $current_page->getLayout()->getUid() ?>"
></div>

<?php if (null !== $this->getParam('token') && $this->getParam('token') instanceof BackBuilder\Security\Token\BBUserToken): ?>
    <script>
        require(['src/tb/init'], function (init) {
            init.load(true);
        });
    </script>
<?php else: ?>
    <script>
        require(['src/tb/init'], function (init) {
            init.listen();
        });
    </script>
<?php endif; ?>
