parameters:
    bbapp.collector.config.class: Symfony\Component\HttpKernel\DataCollector\ConfigDataCollector
    bbapp.collector.request.class: Symfony\Component\HttpKernel\DataCollector\RequestDataCollector
    bbapp.collector.exception.class: Symfony\Component\HttpKernel\DataCollector\ExceptionDataCollector
    bbapp.collector.events.class: Symfony\Component\HttpKernel\DataCollector\EventDataCollector
    bbapp.collector.logger.class: Symfony\Component\HttpKernel\DataCollector\LoggerDataCollector
    bbapp.collector.time.class: Symfony\Component\HttpKernel\DataCollector\TimeDataCollector
    bbapp.collector.memory.class: Symfony\Component\HttpKernel\DataCollector\MemoryDataCollector
    bbapp.collector.router.class: Symfony\Component\HttpKernel\DataCollector\RouterDataCollector

services:
    data_collector.config:
        class: %data_collector.config.class%
        calls:
            - [setKernel, [@?controller]]
        tags:
            - { name: data_collector, template: "BackBuilder/Resources/views/Collector/config.html.twig", id: "config" }
            
#    data_collector.request:
#        class: %data_collector.request.class%
#        tags:
#            - { name: data_collector, template: "BackBuilder/Resources/views/Collector/request.html.twig", id: "request" }
#            - { name: kernel.event_subscriber }
#            
#    data_collector.exception:
#        class: %data_collector.exception.class%
#        tags:
#            - { name: data_collector, template: "BackBuilder/Resources/views/Collector/exception.html.twig", id: "exception" }
#    
#    data_collector.events:
#        class: %data_collector.events.class%
#        tags:
#            - { name: data_collector, template: "BackBuilder/Resources/views/Collector/events.html.twig", id: "events" }
#
#    data_collector.logger:
#        class: %data_collector.logger.class%
#        arguments:  [@?logging]
#        tags:
#            - { name: data_collector, template: "BackBuilder/Resources/views/Collector/logger.html.twig", id: "logger" }
#            - { name: monolog.logger,  channel: profiler }
#    
#    data_collector.time:
#        class: %data_collector.time.class%
#        arguments:  [@?controller]
#        tags:
#            - { name: data_collector, template: "BackBuilder/Resources/views/Collector/time.html.twig", id: "time" }
#            - { name: monolog.logger,  channel: profiler }
#
#    data_collector.memory:
#        class: %data_collector.memory.class%
#        tags:
#            - { name: data_collector, template: "BackBuilder/Resources/views/Collector/memory.html.twig", id: "memory" }
#            
#    data_collector.router:
#        class: %data_collector.router.class%
#        tags:
#            - { name: kernel.event_listener, event: kernel.controller,  method: onKernelController }
#            - { name: data_collector, template: "BackBuilder/Resources/views/Collector/router.html.twig", id: "router" }
            
            