classcontent.include:
  listeners:
    - [BackBuilder\Event\Listener\ClassContentListener, onInclude]

classcontent.update:
  listeners:
    - [BackBuilder\Event\Listener\ClassContentListener, onUpdate]

classcontent.commit:
  listeners:
    - [BackBuilder\Event\Listener\ClassContentListener, onCommit]

classcontent.revert:
  listeners:
    - [BackBuilder\Event\Listener\ClassContentListener, onRevert]

classcontent.onflush:
  listeners:
    - [BackBuilder\Event\Listener\ClassContentListener, onFlushContent]
    - [BackBuilder\Event\Listener\RevisionListener, onFlushContent]
    - [BackBuilder\Event\Listener\IndexationListener, onFlushContent]
    - [BackBuilder\Event\Listener\CacheListener, onFlushContent]
    - [BackBuilder\Event\Listener\MetaDataListener, onFlushContent]
    - [BackBuilder\Event\Listener\RewritingListener, onFlushContent]

classcontent.preremove:
  listeners:
    - [BackBuilder\Event\Listener\ClassContentListener, onPreRemove]

classcontent.prerender:
  listeners:
    - [BackBuilder\Event\Listener\RevisionListener, onPrerenderContent]
    - [BackBuilder\Event\Listener\CacheListener, onPreRenderContent]

classcontent.postrender:
  listeners:
    - [BackBuilder\Event\Listener\CacheListener, onPostRenderContent]

element.file.postremove:
  listeners:
    - [BackBuilder\Event\Listener\ClassContentListener, onRemoveElementFile]

nestednode.page.prerender:
  listeners:
    - [BackBuilder\Event\Listener\CacheListener, onPreRenderPage]

nestednode.page.postrender:
  listeners:
    - [BackBuilder\Event\Listener\CacheListener, onPostRenderPage]

nestednode.page.onflush:
  listeners:
    - [BackBuilder\Event\Listener\MetaDataListener, onFlushPage]
    - [BackBuilder\Event\Listener\RewritingListener, onFlushPage]
    - [BackBuilder\Event\Listener\CacheListener, onFlushPage]

site.layout.prepersist:
  listeners:
    - [BackBuilder\Event\Listener\LayoutListener, onBeforeSave]

site.layout.preupdate:
  listeners:
    - [BackBuilder\Event\Listener\LayoutListener, onBeforeSave]

site.layout.postremove:
  listeners:
    - [BackBuilder\Event\Listener\LayoutListener, onAfterRemove]

revision.postload:
  listeners:
    - [BackBuilder\Event\Listener\RevisionListener, onPostLoad]

element.keyword.render:
  listeners:
    - [BackBuilder\Event\Listener\elementListener, onRender]

frontcontroller.request: 
  listeners:
    - [@rest.listener.body, onRequest]

kernel.request:
  listeners:
    - [@profiler.listener, onKernelRequest]

kernel.exception:
  listeners:
    - [@rest.listener.exception, onKernelException]

kernel.controller:
  listeners:
    - [@rest.listener.validation, onKernelController]

kernel.response:
  listeners:
    - [@profiler.toolbar.listener, onKernelResponse]
    - [@profiler.listener, onKernelResponse]

bbapplication.init:
  listeners:
    - [BackBuilder\DependencyInjection\Listener\ContainerListener, onApplicationInit]
