firewalls:
    bb_area:
        pattern: ^/
        requirements:
            HTTP-X-Requested-With: XMLHttpRequest
            HTTP-X-BB-METHOD: (JsonRpc|Upload)
        provider: bb_user
        bb_auth:
            provider: bb_user
            nonce_dir: security/nonces
            lifetime: 1800
            use_registry: true
    rest_api_area:
        pattern: ^/rest
        provider: public_key
        public_key: ~
        restful: ~
        anonymous: ~
    front_area:
        pattern: ^/
        anonymous: ~
        rememberme: \BackBuilder\Bundle\NextMemberBundle\Listener\RememberMeListener
        provider: nextmember_user
        form_login:
            login_path: /mon-compte/s-identifier.html
        logout:
            handlers: [BackBuilder\Bundle\NextMemberBundle\Logout\LogoutHandler]

providers:
    bb_user:
        entity:
            class: BackBuilder\Security\User
        secret: bb5_secret_key
    public_key:
        entity:
            class: BackBuilder\Security\User

contexts:
    BackBuilder\Security\Context: [StatelessContext, AnonymousContext, BBAuthContext, UsernamePasswordContext, LogoutContext, RestfulContext]

encoders:
    BackBuilder\Security\User: 
        class: Symfony\Component\Security\Core\Encoder\MessageDigestPasswordEncoder
        arguments: 
            algorithm: md5
            encode_as_base64: false
            iterations: 1

acl:
    connection: default
