parameters:
    # bbapp parameters, somes will be set at init of container by BBApplication
    bbapp.context: 'default'
    bbapp.cache.dir: ''
    bbapp.config.dir: ''
    bbapp.locale: 'fr_FR'
    translator.fallback: 'fr'
    # bbapp classes
    bbapp.cachebootstrap.class: BackBuilder\Cache\File\Cache
    bbapp.cachecontrol.class: BackBuilder\Cache\DAO\Cache
    bbapp.config.class: BackBuilder\Config\Config
    bbapp.logger.class: BackBuilder\Logging\Logger
    bbapp.securitycontext.class: BackBuilder\Security\SecurityContext
    bbapp.controller.class: BackBuilder\FrontController\FrontController
    bbapp.renderer.class: BackBuilder\Renderer\Renderer
    bbapp.ed.class: BackBuilder\Event\Dispatcher
    bbapp.rpcserver.class: BackBuilder\Services\Rpc\JsonRPCServer
    bbapp.uploadserver.class: BackBuilder\Services\Upload\UploadServer
    bbapp.urlgenerator.class: BackBuilder\Rewriting\UrlGenerator
    bbapp.translator.class: BackBuilder\Translation\Translator
    bbapp.routing.class: BackBuilder\Routing\RouteCollection
    bbapp.pagebuilder.class: BackBuilder\NestedNode\Builder\PageBuilder
    bbapp.controller_resolver.class: BackBuilder\Controller\ControllerResolver

services:
    cache.bootstrap:
        class:      %bbapp.cachebootstrap.class%
        arguments:  [{cachedir: "%bbapp.cache.dir%"}, "%bbapp.context%"]
    cache-control:
        class:      %bbapp.cachecontrol.class%
        arguments:  [{em: "@em"}, "%bbapp.context%", "@logging"]
    config:
        class:      %bbapp.config.class%
        arguments:  ["%bbapp.base.dir%/Config", "@cache.bootstrap"]
    ed:
        class:      %bbapp.ed.class%
        arguments:  ["@bbapp"]
    logging:
        class:      %bbapp.logger.class%
        arguments:  ["@bbapp"]
    security.context:
        class:      %bbapp.securitycontext.class%
        arguments:  ["@bbapp"]
    controller:
        class:      %bbapp.controller.class%
        arguments:  ["@bbapp"]
    renderer:       
        class:      %bbapp.renderer.class%
        arguments:  ["@bbapp"]
    rpcserver:
        class:      %bbapp.rpcserver.class%
        arguments:  ["@bbapp"]
    uploadserver:
        class:      %bbapp.uploadserver.class%
        arguments:  ["@bbapp"]
    rewriting.urlgenerator:
        class:      %bbapp.urlgenerator.class%
        arguments:  ["@bbapp"]
    translator:
        class:      %bbapp.translator.class%
        arguments:  ["@bbapp", "%bbapp.locale%"]
    pagebuilder:
        class:      %bbapp.pagebuilder.class%
        arguments:  ["@em"]
    
    controller_resolver:
        class:      %bbapp.controller_resolver.class%

    # synthetic services
    site:
        synthetic: true
    bb_session:
        synthetic: true
    routing:
        synthetic: true
    mailer:
        synthetic: true