<!DOCTYPE html>
<html>
<head>
    <title>Error 404 (Not Found)</title>
    <meta charset="utf-8">
    <link rel="shortcut icon" href="{{ this.getResourceUrl('/img/favicon.ico') }}">
</head>
<body>
    <!-- BB5 SITE WRAPPER -->
    <div id="bb5-site-wrapper">
        <!-- BEGIN bodywrapper: .container -->
        <div class="container" id="body-wrapper">
            <!-- bodywrapper -->
            <div class="row" id="bb5-mainLayoutRow">
                <div class="col-md-12">
                    <section role="main" class="section">
                        <h1>Page not found&hellip;</h1>
                        <div class="announcement-wrapper">
                            <p>It seems that this page does not exist or is not published yet.</p>
                        </div>
                    </section>
                </div>
            <!-- /end bodywrapper -->
        </div>
        <!-- END bodywrapper -->
    </div>
    <!-- END BB5 SITE WRAPPER -->
</body>
</html>
