<!DOCTYPE html>
<html>
<head>
    <title><?php echo $this->getCurrentSite()->getLabel(); ?></title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="<?php echo $this->getResourceUrl('css/style_reset.css'); ?>">
</head>
<body>
    <?php echo $this->bb5toolbar(); ?>

    <!-- BB5 SITE WRAPPER -->
    <div id="bb5-site-wrapper">
        <!-- BEGIN bodywrapper: .container -->
        <div class="container" id="body-wrapper">
            <!-- bodywrapper -->
            <div class="row" id="bb5-mainLayoutRow">
                <div class="span12">
                    <section role="main" class="section">
                        <h1>Une erreur est survenue&hellip;</h1>
                        <div class="announcement-wrapper">
                            <p><?php echo $this->error_message; ?></p>
                            <?php echo $this->error_trace; ?>
                        </div>
                        <hr>
                        <div class="announcement-box">
                            <p>Veuillez nous excuser pour la gêne occasionnée.</p>
                        </div>
                    </section>
                </div>
            <!-- /end bodywrapper -->
        </div>
        <!-- END bodywrapper -->
    </div>
    <!-- END BB5 SITE WRAPPER -->
</body>
</html>
