<!DOCTYPE html>
<html>
<head>
    <title><?php echo $this->getCurrentSite()->getLabel(); ?></title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="<?php echo $this->getResourceUrl('css/style_reset.css'); ?>">
</head>
<body>
    <?php echo $this->bb5toolbar(); ?>

    <!-- BB5 SITE WRAPPER -->
    <div id="bb5-site-wrapper">
        <!-- BEGIN bodywrapper: .container --><div class="container-fluid" id="body-wrapper">
            <!-- bodywrapper -->
            <div class="row" id="bb5-mainLayoutRow">
                <div class="span12"><?php echo $this->container()->first(); ?></div>
            </div>
            <!-- /end bodywrapper -->
        </div>
        <!-- END bodywrapper -->
    </div>
    <!-- END BB5 SITE WRAPPER -->
</body>
</html>