<link class="bootstrapStylesheet" rel="stylesheet/less" type="text/css" href="<?php echo $this->getUri('ressources/themes/default/less/bootstrap.less?d='.date('sihdm')); ?>">
<script src="<?php echo $this->getUri('js/less-1.3.0.min.js'); ?>" type="text/javascript"></script>
<!--CSS: common-->
<!--CSS: BB4 bootstrap-->
<link class="protoStylesheet" href="<?php echo $this->getUri('ressources/themes/default/css/bb4-proto.css'); ?>" rel="stylesheet">

<link class="baseStylesheet" rel="stylesheet" href="<?php echo $this->getUri('css/style.css'); ?>">
<!--CSS: Aloha-->
<link rel="stylesheet" href="<?php echo $this->getUri('js/aloha/css/aloha.css'); ?>" type="text/css">

<!--CSS: BB4 interface-->
<link rel="stylesheet" href="<?php echo $this->getUri('css/bb4_gen.css'); ?>">
<link rel="stylesheet" href="<?php echo $this->getUri('css/colorpicker.css'); ?>">

<!--CSS: jQuery UI-->
<link rel="stylesheet" href="<?php echo $this->getUri('css/smoothness/jquery-ui-1.8.17.custom.css'); ?>">
<!--CSS: jQuery loadmask-->
<link rel="stylesheet" href="<?php echo $this->getUri('css/loadmask/jquery.loadmask.css'); ?>">

<script src="<?php echo $this->getUri('js/libs/modernizr-2.0.6.min.js'); ?>"></script>

<!-- SCRIPTs -->
<script>window.jQuery || document.write('<script src="<?php echo $this->getUri('js/libs/jquery-1.7.1.min.js'); ?>"><'+'/script>')</script>

<!-- scripts concatenated and minified via ant build script-->
<!--script src="<?php echo $this->getUri('js/plugins.js'); ?>"></script-->
<script src="<?php echo $this->getUri('js/libs/jquery-ui-1.8.17.custom.min.js'); ?>"></script>
<script src="<?php echo $this->getUri('js/libs/jquery.bxSlider.min.js'); ?>"></script>

<script src="<?php echo $this->getUri('js/script.js'); ?>"></script>
<script src="<?php echo $this->getUri('js/libs/jquery.loadmask.min.js'); ?>"></script>
<script src="<?php echo $this->getUri('js/libs/jquery.jstree.js'); ?>"></script>
<script src="<?php echo $this->getUri('js/libs/jquery.jscrollpane.min.js'); ?>"></script>
<script src="<?php echo $this->getUri('js/libs/json2.js'); ?>"></script>
<script src="<?php echo $this->getUri('js/libs/jquery.jsonrpc.js'); ?>"></script>
<script src="<?php echo $this->getUri('js/libs/jquery.filedrop.js'); ?>"></script>
<script src="<?php echo $this->getUri('js/libs/jquery.templates.js'); ?>"></script>
<script src="<?php echo $this->getUri('js/colorpicker.js'); ?>"></script>





<!-- end SCRIPTs-->
<script src="<?php echo $this->getUri('js/bb.js'); ?>"></script>
<script src="<?php echo $this->getUri('js/aloha/lib/aloha.js'); ?>"
data-aloha-plugins="common/format, common/link, common/highlighteditables, extra/bbselector" type="text/javascript"></script>
<script src="<?php //echo $this->getUri('js/AlohaManager.js'); ?>" type="text/javascript"></script>
<style type="text/css">
    .menu {margin-top:30px; height: 40px; margin :2px; width : auto;}
    .menu li {list-style: none; display: inline-block; border: 1px solid #E2E6F0; margin: 10px}
    .menu .actionBtn {margin: 10px; padding: 20px; text-decoration: none}
    .clearBox{clear:both}
    .bb4ResizableLayout {margin-bottom: 1px}
    .bb4ResizableLayout.selected {outline : 2px dotted red}
    .bb4-ui-resizable-helper {outline: 3px solid #00A8FF}
    .splitMenu {border: 1px solid #E2E6F0; width:300px; height:100px; background-color: #e6e6e6; position: absolute; top:13px; left: 33px}
    .bb4ResizableLayout.selectedLayout{outline: 3px groove #00A8FF; position:relative;}
    .bb4ResizableLayout .layoutTitle{ margin:0px}
    .test{background-color: #E4E7EF; outline: 1px solid blue}
    .noMargin{ margin-left: 0; margin-right: 0; }
    .alpha { margin-left: 0;}
    .omega { margin-right: 0;}
    #bb5-templateHeader{ margin-bottom: 10px}
    #bb5-templateFooter{margin-top: 10px}
</style>

<div id="bbSupraWrapper" style="visibility:hidden" data-site="<?php echo $this->layout()->getSite()->getUid(); ?>" data-layout="<?php echo $this->layout()->getUid(); ?>" data-page="<?php echo $this->currentpage()->getUid();?>" data-breadcrumb="<?php echo join('-', $this->currentpage()->getBreadcrumb_uids()); ?>">
    <div id="bbWrapper">
        <!--Logo-->
        <p id="bbLogo"><a target="_blank" href="http://www.backbuilder.fr/"><span class="visuallyhidden">BackBuilder</span></a></p>
        <!--Login-->
        <div id="bbLogin">
            <p>M Loremispum Irridium
                <button title="Log Off">x</button>
            </p>
        </div>
        <div id="bbShortcuts">
            <button class="bbBtn_paleblue bbBtnSave"><span></span>Enregistrer</button>
            <button class="bbBtn_paleblue bbBtnRedo"><span></span>Rétablir</button>
            <button class="bbBtn_paleblue bbBtnCancel"><span></span>Annuler</button>
        </div>
        <!-- -->
        <div id="bbTabsWrapper">
            <ul>
                <li><a class="tabBtn" href="#structure">Gabarits</a></li>
                <li><a class="tabBtn" href="#theming">Themes</a></li>
                <li><a class="tabBtn" href="#zoning">Gestion des blocs</a></li>
                <li><a class="tabBtn" href="#edition">Edition</a></li>
                <li><a class="tabBtn" href="#status">Validation et statut</a></li>
                <li><a class="tabBtn" href="#me">Mon espace</a></li>
            </ul>
            <div class="clearfix" id="bbTabsPanels">
                <!-- BEGIN 01 -->
                <div id="structure">
                    <!-- 01 -->
                    <div class="bbArea_1 bbAreaTemplateChoice">
                        <!-- -->
                        <fieldset>
                            <legend>Choisir un gabarit</legend>
                            <div class="bbAreaContent">
                                <div id="bbGridSlideWrapper">
                                    <ul class="bbGridSlide" id="userTemplate"></ul>
                                </div>
                            </div>
                            <div class="bbDrawerContainer"><a class="bbDrawerBtn showTplModel" href="#">Modèles disponibles<span></span></a>
                                <div id="tplModelContainer" class="bbDrawerData">
                                    <ul id="bbModelTplGridSlide" class="bbGridSlide"></ul>
                                </div>
                            </div>
                        </fieldset>
                        <!-- -->
                    </div>
                    <!-- 02 -->
                    <div class="bbArea_2 bbAreaTemplate">
                        <!-- -->
                        <fieldset>
                            <legend>Gabarit :</legend>
                            <p class="bbEditName">
                                <input id="layoutNameField" type="text" disabled="disabled" value="Homepage">
                                <button title="Editer le nom" class="bbBtn_smallSquare editLayoutNameBtn bbBtnEditSmall"><span></span></button>
                            </p>
                            <div class="bbAreaContent">
                                <p>
                                    <button class="bbBtn_square bbBtnSave bbBtnGridSave"><span></span>Enregistrer</button>
                                </p>
                                <p>
                                    <button class="bbBtn_square bbBtnDuplicate"><span></span>Dupliquer</button>
                                </p>
                                <p>
                                    <button class="bbBtn_square bbBtnDel"><span></span>Supprimer</button>
                                </p>
                            </div>
                        </fieldset>
                        <!-- -->
                    </div>
                    <!-- 03 -->
                    <div class="bbArea_3 bbAreaComponent">
                        <!-- -->
                        <fieldset>
                            <legend>Zone :</legend>
                            <p class="bbEditName">
                                <input id="zoneNameField" disabled="disabled" type="text" value="Homepage">
                                <button title="Editer le nom" class="bbBtn_smallSquare bbBtnEditSmall editZoneName"><span></span></button>
                            </p>
                            <div class="bbAreaContent">
                                <p>
                                    <button class="bbBtn_square bbBtnSplitH"><span></span>Scinder horizontalement</button>
                                </p>
                                <p>
                                    <button class="bbBtn_square bbBtnSplitV"><span></span>Scinder verticalement</button>
                                </p>
                                <p>
                                    <button class="bbBtn_square bbBtnDelCol"><span></span>Supprimer la zone</button>
                                </p>
                            </div>
                        </fieldset>
                        <!-- -->
                    </div>
                    <!-- 04 -->
                    <div class="bbArea_4 bbAreaGrid">
                        <!-- -->
                        <fieldset>
                            <legend>Grille :</legend>
                            <div class="bbAreaContent">
                                <p>Largeur de la grille : <span class="gridSize"><strong>###</strong></span> (pixels)</p>
                                <p>
                                    <label class="bbLabelCheckbox">
                                        <input class="showGridBtn" type="checkbox" checked="checked" name="grid">
                                        <span class="bbLabelContent">Afficher la grille</span></label>
                                </p>
                            </div>
                            <div class="bbDrawerContainer"><a class="bbDrawerBtn showGridEditorBtn" href="#">Modifier la grille <span></span></a>
                                <div class="bbDrawerData gridEditor">
                                    <div class="bbDrawerDataPadding">
                                        <p>
                                            <label>Nombre de colonnes</label>
                                            <span class="columnNumber"><strong>12</strong></span></p>
                                        <p>
                                            <label>Largeur (pixels)</label>
                                            <input type="text" id="colSizeField" value="30" size="2">
                                            <button title="Incrémenter le nombre" class="bbBtn_numeric gridColBtn upAction">+</button>
                                            <button title="Décrémenter le nombre" class="bbBtn_numeric gridColBtn downAction">-</button>
                                        </p>
                                        <p>
                                            <label>Gouttière (pixels)</label>
                                            <input type="text" id="gutterSizeField" value="10" size="2">
                                            <button title="Incrémenter le nombre" class="bbBtn_numeric gutterBtn upAction">+</button>
                                            <button title="Décrémenter le nombre" class="bbBtn_numeric gutterBtn downAction">-</button>
                                        </p>
                                        <p>
                                            <button class="bbBtn_square bbBtnGridValidate">Valider</button>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        <!-- -->
                    </div>
                    <!-- 05 off -->
                    <!-- -->
                </div>
                <!-- END 01 -->
                <!-- BEGIN 02 -->
                <div id="theming">
                    <div class="bbArea_1 bbAreaThemingData">
                        <fieldset>
                            <legend>Edition du thème courant</legend>
                            <div class="lessVariablesEditables"></div>
                            <div class="bbDrawerContainer"><a class="bbDrawerBtn showTplTheme" href="#">Thèmes disponibles<span></span></a>
                                <div id="tplThemeContainer" class="bbDrawerData" style="display: none; ">
                                    <ul id="bbThemeTplGridSlide" class="bbGridSlide">
                                        
                                    </ul>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                    <div class="bbArea_2 bbAreaTemplate">
                        <!-- -->
                        <fieldset>
                            <legend>Thème :</legend>
                            <p class="bbEditThemeName">
                                <input id="themeNameField" type="text" disabled="disabled" value="default">
                                <button title="Editer le nom" class="bbBtn_smallSquare editThemeNameBtn bbBtnEditSmall"><span></span></button>
                            </p>
                            <div class="bbAreaContent">
                                <p>
                                    <button class="bbBtn_square bbBtnSave bbBtnGridSaveTheme"><span></span>Enregistrer</button>
                                </p>
                            </div>
                        </fieldset>
                        <!-- -->
                    </div>
                </div>
                <!-- END 02 -->
                <!-- BEGIN 03 -->
                <div id="zoning">
                    <!-- -->
                    <div class="bbArea_1 bbAreaWelding">
                        <div class="bbAreaInner alignVertMid">
                            <select id="contentCatContainer" style="margin:auto;" size="6">
                                <option value="Accueil">Accueil</option>
                                <option value="Grilles">Grilles</option>
                                <option value="Colonnes">Colonnes</option>
                                <option value="Liens">Liens</option>
                                <option value="Media">Media</option>
                                <option value="Boites colonnes">Boites colonnes</option>
                                <option value="Boites centre">Boites centre</option>
                            </select>
                        </div>
                        <!-- -->
                    </div>
                    <div class="bbArea_2">
                        <!-- -->
                        <fieldset>
                            <legend>Blocs pour l'item sélectionné ci-contre</legend>
                            <div class="bbAreaContent">
                                <div id="bbBlockSlideWrapper">
                                    <ul class="bbGridSlide" id="bbBlockSlide"></ul>
                                </div>
                            </div>
                        </fieldset>
                        <!-- -->
                    </div>
                    <div class="bbArea_3">
                        <div class="draggableContent"></div>
                        <div class="draggableContent"></div>
                        <div class="draggableContent"></div>
                    </div>
                </div>
                <!-- END 03 -->
                <div id="edition">
                    <!-- 01 -->
                    <div class="bbArea_1 bbAreaTemplate">
                        <!-- -->
                        <fieldset>
                            <legend>Edition :</legend>
                            <div class="bbAreaContent">
                                <p>
                                    <button class="bbBtn_square bbBtnPage"><span></span>Nouvelle page</button>
                                </p>
                                <p>
                                    <button class="bbBtn_square bbBtnDel"><span></span>Supprimer</button>
                                </p>
                            </div>
                        </fieldset>
                        <!-- -->
                    </div>
                    <div class="bbArea_2 bbAreaTemplate">
                        <!-- -->
                        <fieldset>
                            <legend>Navigation :</legend>
                            <div class="bbAreaContent">
                                <p>
                                    <button class="bbBtn_square bbBtnDir"><span></span>Arborescence</button>
                                </p>
                                <p>
                                    <button class="bbBtn_square bbBtnMedia"><span></span>Médiathèque</button>
                                </p>
                                <p>
                                    <label class="bbLabelCheckbox">
                                        <input class="showContentEditionBtn" type="checkbox" name="content_edition">
                                        <span class="bbLabelContent">Afficher</span>
                                    </label>
                                </p>
                            </div>
                        </fieldset>
                        <!-- -->
                    </div>
                    
                    <div id="aloha" class="containAloha" style="position: relative;display: inline-block;"></div>
                </div>
                <div id="status">
                    <p>Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade. Messenger bag gentrify pitchfork tattooed craft beer, iphone skateboard locavore carles etsy salvia banksy hoodie helvetica. DIY synth PBR banksy irony. Leggings gentrify squid 8-bit cred pitchfork. Williamsburg banh mi whatever gluten-free, carles pitchfork biodiesel fixie etsy retro mlkshk vice blog. Scenester cred you probably haven't heard of them, vinyl craft beer blog stumptown. Pitchfork sustainable tofu synth chambray yr.</p>
                </div>
                <div id="me">
                    <p>Trust fund seitan letterpress, keytar raw denim keffiyeh etsy art party before they sold out master cleanse gluten-free squid scenester freegan cosby sweater. Fanny pack portland seitan DIY, art party locavore wolf cliche high life echo park Austin. Cred vinyl keffiyeh DIY salvia PBR, banh mi before they sold out farm-to-table VHS viral locavore cosby sweater. Lomo wolf viral, mustache readymade thundercats keffiyeh craft beer marfa ethical. Wolf salvia freegan, sartorial keffiyeh echo park vegan.</p>
                </div>
            </div>
            <!-- -->
            <!-- Extra area -->
            <div id="bbPathWrapper">
                <button class="bbBtn_void bbBtnPathUp"><span></span></button>
                <p id="bbPath"><a class="bbPath_kindBlock" href="#">Lorem ipsum</a> <a class="bbPath_kindBlock" href="#">Lorem ipsum</a> <a class="bbPath_kindBlock bbPath_kindActive" href="#">Lorem ipsum</a></p>
                <button class="bbBtn_void bbBtnClose"><span></span></button>
            </div>
            <!-- End Extra area -->
            <!-- -->
        </div>
        <!-- -->

        <!-- Dialog: popin -->
        <div id="dialog-confirm" class="bbPopinContainer bbPopinConfirm" title="">
            <p>Voulez vous ajouter ce modèle à la liste de vos gabarits&nbsp;?</p>
        </div>
        <!-- End popin --->

        <!-- bb-ui-bbpagebrowser: dialog -->
        <div id="dialog-treeview" class="bbPopinContainer" title="Arborescence">
            <div class="filetree" id="browser"></div>
        </div>
        <!-- end bb-ui-bbpagebrowser: dialog -->

        <!-- bb-ui-bbselector: dialog for media -->
        <div id="dialog-media-selector" class="bbPopinContainer" title="Sélecteur">
            <!-- dialog tabs -->
            <div id="bbDialogTabsWrapper">
                <ul></ul>
                <div class="clearfix" id="bbDialogTabsPanels">
                </div>
            </div>
            <!-- End dialog dialog for media -->

        </div>
        <!-- end bb-ui-bbselector: dialog -->

        <!-- bb-ui-bbpagebrowser: form -->
        <div id="bb-ui-bbpagebrowser-form" class="bbPopinContainer" title="">
            <form>
            <fieldset>
                <label for="bb-ui-bbpagebrowser-form-title">Titre</label>
                <input type="text" id="bb-ui-bbpagebrowser-form-title" name="title" value="" style="width: 100%; margin-bottom: 10px;" />

                <label for="bb-ui-bbpagebrowser-form-url">URL</label>
                <input type="text" id="bb-ui-bbpagebrowser-form-url" name="url" value="" style="width: 100%; margin-bottom: 10px;" />

                <label for="bb-ui-bbpagebrowser-form-layout">Layout</label>
                <select id="bb-ui-bbpagebrowser-form-layout" name="layout" style="width: 100%; margin-bottom: 10px;"></select>

            </fieldset>
            </form>
        </div>
        <!-- end bb-ui-bbpagebrowser: form -->

        <!-- bb-ui-bbselector: dialog for link -->
        <div id="dialog-link-selector" class="bbPopinContainer" title="Sélecteur">
            <!-- dialog tabs -->
            <div id="bbDialogTabsWrapper">
                <ul></ul>
                <div class="clearfix" id="bbDialogTabsPanels">
                </div>
            </div>
            <!-- End dialog dialog for link -->

        </div>
        <!-- end bb-ui-bbselector: dialog -->

        <!-- bb-ui-bbselector: tabs -->
        <div id="bb-ui-bbselector-tabs-tpl" style="display:none;">
            <li><a href="#bbLinkInternal">Liens internes</a></li>
            <li><a href="#bbLinkExternal">Liens externes</a></li>
            <li><a href="#bbMedia">Média</a></li>
        </div>
        <!-- end bb-ui-bbselector: tabs -->

        <!-- bb-ui-bbpageselector: panel -->
        <div id="bb-ui-bbpageselector-panel-tpl" style="display:none;">
            <!-- -->
            <div class="bbArea_linkInt">
                <!-- -->
                <div class="bbPaneWrapper">
                    <div class="bbPaneTree">
                        <!-- :nth-child(1) -->
                        <p>
                            <select>
                                <option value="">Sélectionner un site ...</option>
                            </select>
                        </p>
                        <!-- tree links -->
                        <div class="filetree" id="browserLinks"></div>
                        <!-- end tree links -->
                        <!-- end :nth-child(1) -->
                    </div>
                    <div class="bbPaneMain"></div>
                </div>
                <!-- -->
            </div>
            <!-- -->
        </div>
        <!-- end bb-ui-bbpageselector: panel -->

        <!-- bb-ui-bbpageselector: view -->
        <div id="bb-ui-bbpageselector-view-tpl" style="display:none;">
            <p class="bbSortWrapper"><button class="bbBtn_square bbBtnSortList bbBtnDisabled"><span></span></button> <select title="Nombre d'items à l'affichage"><option>20</option><option>50</option></select></p>
            <table class="tableData0x">
                <caption>&nbsp;</caption>
                <thead>
                    <tr>
                        <th title="Lancer le tri" class="sort_title">Répertoire courant</th>
                        <th title="Lancer le tri" class="sort_created">Date de création</th>
                        <th title="Lancer le tri" class="sort_modified">Date de modification</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
            <!-- end :nth-child(2) -->
        </div>
        <!-- end bb-ui-bbpageselector: view -->

        <!-- bb-ui-bbpageselector: viewrow -->
        <div id="bb-ui-bbpageselector-viewrow-tpl" style="display:none;">
            <table>
                <tr>
                    <td><a href="" target="_blank"><span></span>${title}</a></td>
                    <td>${created}</td>
                    <td>${modified}</td>
                    <td><button value="${uid}" class="bbBtn_square">Sélectionner</button></td>
                </tr>
            </table>
        </div>
        <!-- end bb-ui-bbpageselector: viewrow -->

        <!-- bb-ui-bblinkselector: panel -->
        <div id="bb-ui-bblinkselector-panel-tpl" style="display:none;">
            <div class="bbArea_linkExt">
                <!-- -->
                <div class="bbArea_linkExt">
                    <fieldset>
                        <legend>Sélectionner un lien externe</legend>
                        <p>
                            <label for="bbForm001">Lien : </label>
                            <input type="text" id="bbForm001" />
                        </p>
                        <p>
                            <label for="bbForm002">Titre : </label>
                            <input type="text" id="bbForm002" />
                        </p>
                        <p>
                            <button class="bbBtn_square bbBtnAdd"><span></span>Sélectionner</button>
                        </p>
                    </fieldset>
                </div>
                <!-- -->
            </div>
            <!-- -->
        </div>
        <!-- end bb-ui-bblinkselector: panel -->

        <!-- bb-ui-bbmediaselector: panel -->
        <div id="bb-ui-bbmediaselector-panel-tpl" style="display:none;">
            <!-- -->
            <div class="bbArea_media">
                <!-- -->
                <div class="bbPaneWrapper">
                    <div class="bbPaneTree">
                        <!-- tree media -->
                        <div class="filetree" id="browserMedia"></div>
                        <!-- end tree media -->
                        <!-- end :nth-child(1) -->
                    </div>
                    <div class="bbPaneMain"></div>
                </div>
                <!-- -->
            </div>
            <!-- -->
        </div>
        <!-- end bb-ui-bbmediaselector: panel -->

        <!-- bb-ui-bbmediaselector: view -->
        <div id="bb-ui-bbmediaselector-view-tpl" style="display:none;">
            <!-- :nth-child(2) -->
            <p class="bbActionWrapper">
                <button class="bbBtn_square bbBtnEdit"><span></span>Modifier le dossier</button>
                <button class="bbBtn_square bbBtnDel"><span></span>Supprimer le dossier</button>
                <button class="bbBtn_square bbBtnDir"><span></span>Ajouter le dossier</button>
                <button class="bbBtn_square bbBtnMedia"><span></span>Ajouter un media</button>
                <button class="bbBtn_square bbBtnServer"><span></span>Importer depuis le serveur</button>
            </p>
            <div class="bbToolbarWrapper">
                <p class="bbToolbarCaption"></p>
                <p class="bbToolbarNav"></p>
                <p class="bbSortWrapper"><button class="bbBtn_square bbBtnSortGrid"><span></span></button> <button class="bbBtn_square bbBtnSortList"><span></span></button> <select title="Nombre d'items à l'affichage"><option>20</option><option>50</option></select></p>
            </div>
        </div>
        <!-- end bb-ui-bbmediaselector: view -->

        <!-- bb-ui-bbmediaselector: viewgrid -->
        <div id="bb-ui-bbmediaselector-viewgrid-tpl" style="display:none;">
            <ul class="bbListMedia bbListMediaIsGrid clearfix"></ul>
        </div>
        <!-- end bb-ui-bbmediaselector: viewgrid -->

        <!-- bb-ui-bbmediaselector: viewlist -->
        <div id="bb-ui-bbmediaselector-viewlist-tpl" style="display:none;">
            <ul class="bbListMedia bbListMediaIsList clearfix"></ul>
        </div>
        <!-- end bb-ui-bbmediaselector: viewlist -->
        
        <div id="bb-zonelayout-properties" style="display:none;">
            <form>
            	<label for="bb-zonelayout-property-ismainzone">
            		<span>Main layout zone:
	            		<input type="checkbox" id="bb-zonelayout-property-ismainzone" value="1" />
	            	</span>
            	</label>
            	<label for="bb-zonelayout-property-accept">
            		<span>Accepted content type(s):</span>
            		<select id="bb-zonelayout-property-accept" multiple="multiple">
            			<option value="">All</option>
            		</select>
            	</label>
            	<label for="bb-zonelayout-property-maxentry">
            		<span>Max accepted entries: <br/><em>(leave empty for unlimited)</em>:</span>
            		<input type="text" id="bb-zonelayout-property-maxentry" />
            	</label>
            	<label for="bb-zonelayout-property-defaultcontent">
            		<span>Default content:</span>
            		<select id="bb-zonelayout-property-defaultcontent">
            			<option value="">None</option>
            			<option value="inherited">Same as parent</option>
            		</select>
            	</label>
            </form>
        </div>
    </div>
</div>
<!-- OLDIEs installing Chrome for IE -->
<!--[if lt IE 7 ]>
        <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
        <script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
<![endif]-->
<script type="text/javascript">
   bb.init('<?php echo $this->getUri(); ?>');
   //AlohaManager.init();
   $(bb).bind("ready",function() {
       bb.frontApplication.init();
   });
</script>
