<!-- JS -->
<!-- jQuery stuff -->
<!-- CUSTOM JS -->
<script type="text/javascript" src="js/helper.js"></script>
<script type="text/javascript" src="js/script.js"></script>
<!--[if (gte IE 6)&(lte IE 8)]>
    <script type="text/javascript" src="js/selectivizr-min.js"></script>
<![endif]-->
<!-- ADS THIS-->
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-502286753ee742e2"></script>
<!-- END JS -->