<footer class="footerWrapper">
    <div class="outerContainer">
        <div class="container">
            <div class="row-fluid">
                <div class="span12">
                    <div class="footer-inner">
                        <!-- copyright -->
                        <p class="footer-copyright">Copyright &copy; 2012 Votre nom ici. Tous droits réservés.</p>
                        <!-- end copyright -->
                        <p class="footer-author-theme"><a href="#">Pure Theme</a> by <a href="#">Lp-digital</a></p>
                        <!-- end footer inner -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>