<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="description" content="">
<!-- Mobile IE allows us to activate ClearType technology for smoothing fonts for easy reading -->
<meta http-equiv="cleartype" content="on">
<!-- Mobile viewport optimized: h5bp.com/viewport -->
<!--meta name="viewport" content="width=device-width"-->
<meta name="viewport" content="initial-scale=1">
<!-- CSS -->
<!-- Reset by BoilerPlate -->
<link rel="stylesheet" type="text/css" href="/css/style_reset.css">
<!-- EXTRA CSS -->
<!-- Gen -->
<link rel="stylesheet" type="text/css" href="/css/gen.css">
<link rel="stylesheet/less" type="text/less" href="/css/styles_custom.less">
<!-- Bootstrap: GRID -->
<link rel="stylesheet" href="/css/bootstrap-grid.css">
<link rel="stylesheet" href="/css/bootstrap-resp-grid.css">
<script type="text/javascript" src="/js/less-1.3.0.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/js/libs/respond.min.js"></script>
<script type="text/javascript" src="/js/libs/modernizr.custom.2.6.0.js"></script>
<script type="text/javascript" src="/js/swfobject.js"></script>