<header class="headerWrapper">
    <div class="outerContainer">
        <div class="row-fluid">
            <div class="span12">
                <h1 class="logo-wrapper"><a href="#"><a href="<?php echo $this->getUri(); ?>"><img src="<?php echo $this->getUri('img/logo.png'); ?>" alt="Le Journal de l'Eco."></a></h1>
                <ul id="header-nav-extra" class="nav">
                    <li><a href="#">A propos</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
                <form role="search">
                    <div class="section-main-search">
                        <fieldset>
                                <legend class="visuallyhidden">Recherche</legend>
                                <p><label for="form-search-sitewide" class="visuallyhidden">Rechercher sur ce blog</label><input type="text" id="form-search-sitewide" value="Rechercher..."><button class="ico-search" type="submit" title="Lancer la recherche"><i></i></button></p>
                        </fieldset>
                    </div>
                </form>
                <?php echo $this->partial('Partials/navbar.phtml'); ?>
                <div class="clear-blocks"></div>
            </div>
        </div>
    </div>
</header>
