<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]>	<html class="no-js lt-ie10 lt-ie9 lt-ie8 lt-ie7" lang="fr"> <![endif]-->
<!--[if IE 7]>	<html class="no-js lt-ie10 lt-ie9 lt-ie8" lang="fr"> <![endif]-->
<!--[if IE 8]>	<html class="no-js lt-ie10 lt-ie9" lang="fr"> <![endif]-->
<!--[if IE 9]>  <html class="no-js lt-ie10" lang="fr"> <![endif]-->

<!--[if IEMobile 7 ]>	<html class="no-js iem7" lang="fr"> <![endif]-->
<!--[if (gt IEMobile 7)&(gt IE 9)|!(IEMobile)]><!--> <html class="no-js" lang="fr"> <!--<![endif]-->
