<nav role="navigation" class="clearfix">
    <ul id="nav-mobile">
        <li><a href="#" class="ico-menu-big"><i>Menu</i></a></li>
        <li><a href="#" class="ico-search-big"><i>Recherche</i></a></li>
    </ul>
    <ul id="nav-primary" class="clearfix">
        <li><a href="#">Accueil</a></li>
        <li><a href="#">Courses</a></li>
        <li class="nav-selected"><a href="#">Entrainement</a></li>
        <li><a href="#">Plans</a></li>
        <li><a href="#">Tests matériel</a></li>
        <li><a href="#">Partenaires</a></li>
    </ul>
</nav>